// <auto-generated />
using System;
using DataEntryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324223810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DataEntryApp.Models.Entry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeamWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("CTDIvol")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DLP")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAbdominopelvicMasses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAbdominopelvicTrauma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcuteAbdomen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAecUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImageQualityAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KV")
                        .HasColumnType("REAL");

                    b.Property<double>("MAS")
                        .HasColumnType("REAL");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Pitch")
                        .HasColumnType("REAL");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencePhantom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RotationTime")
                        .HasColumnType("REAL");

                    b.Property<string>("ScanningMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ScanningRange")
                        .HasColumnType("REAL");

                    b.Property<double>("SliceThickness")
                        .HasColumnType("REAL");

                    b.Property<string>("SpecificHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
